name: Deploy to Amazon EC

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "ECR image tag to deploy (usually the Git commit SHA)"
        required: true

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-ecs-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: "061039798341"
      ECR_REPOSITORY: medusa-app
      ECS_CLUSTER: medusa-app-ecs-cluster
      ECS_SERVICE: medusa-app-service
      ECS_TASK_FAMILY: medusa-app-task
      CONTAINER_NAME: medusa-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::061039798341:role/github-oidc-policy
          aws-region: ${{ env.AWS_REGION }}

      - name: Build image URI
        run: |
          echo "IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${{ inputs.image_tag }}" >> $GITHUB_ENV

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $ECS_TASK_FAMILY \
            --query taskDefinition > task-definition.json

      - name: Render new task definition with updated image
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.IMAGE_URI }}

      - name: Deploy task definition to ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true